export const PLANS_LIST = {
  '12_MONTHS': {
    name: '12 Months',
    amountPerMonth: 99,
    monthCount: 12,
    freeMonths: 3,
    PLAN_NAME: '12_MONTHS',
  },
  '6_MONTHS': {
    name: '6 Months',
    amountPerMonth: 149,
    monthCount: 6,
    freeMonths: 2,
    PLAN_NAME: '6_MONTHS',
  },
  '3_MONTHS': {
    name: '3 Months',
    amountPerMonth: 199,
    monthCount: 3,
    freeMonths: 1,
    PLAN_NAME: '3_MONTHS',
  },
};

export const AD_PLANS_LIST = {
  '1_DAY': {
    name: '24x1',
    description: 'Top listed for 1 Day',
    price: 30,
    actualPrice: 40,
    day: 1,
    adBalance: 1,
    additionalText: 'Full Days',
    PLAN_NAME: '1_DAY',
    type: 'PAID',
    score: 4000,
  },
  '7_DAY': {
    name: '24x7',
    description: 'Top listed for 7 Days',
    price: 200,
    actualPrice: 280,
    day: 7,
    adBalance: 1,
    additionalText: 'Full Days',
    PLAN_NAME: '7_DAY',
    type: 'PAID',
    score: 6000,
  },
  '15_DAY': {
    name: '24x15',
    description: 'Top listed for 15 Days',
    price: 400,
    actualPrice: 600,
    day: 15,
    adBalance: 1,
    additionalText: 'Full Days',
    PLAN_NAME: '15_DAY',
    type: 'PAID',
    score: 12000,
  },
  '30_DAY': {
    name: '24x30',
    description: 'Top listed for 30 Days',
    price: 700,
    actualPrice: 1200,
    day: 30,
    adBalance: 1,
    additionalText: 'Full Days',
    PLAN_NAME: '30_DAY',
    type: 'PAID',
    score: 36000,
  },
};
